// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.513
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func GenericCardSkeleton(id string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<sl-card class=\"ltr card-image bg-base-100 shadow-sm w-full\" id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(id))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><div slot=\"image\"><sl-skeleton class=\"w-32 h-32\" style=\"--border-radius: 0;\"></sl-skeleton></div><div class=\"w-56 sm:w-60 h-32 md:w-64 flex-initial mx-2\"><div class=\"h-full flex flex-col justify-evenly\"><div class=\"mb-1 flex flex-col justify-start gap-2\"><sl-skeleton effect=\"pulse\"></sl-skeleton> <sl-skeleton class=\"w-80%\" effect=\"pulse\"></sl-skeleton></div><div class=\"w-full flex flex-row flex-wrap gap-1\"><sl-skeleton class=\"w-full\" effect=\"pulse\"></sl-skeleton></div></div></div></sl-card>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
